### ISSUE TITLE
Port over Rosalie's changes

### ISSUE THREAD

**Issue by mudlord** [mudlord/pj64-parallelrdp#3]
Rosalie did some very nice changes that I should have done.
It was nice of them to do.

**Comment by mudlord** [comment]
Done. Thanks to @Rosalie241 for doing all the changes when I was gone from things.

**Comment by Rosalie241** [comment]
Thank you for noticing the changes and pulling them :heart:

**Comment by mudlord** [comment]
Its okay :)
